services:
  db:
    image: postgres:15-alpine
    container_name: tcc-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tcc_98aj
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d/

  api:
    build: .
    container_name: tcc-fastapi
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/tcc_98aj
    volumes:
      - ./app:/code/app
    depends_on:
      - db
  adminer:
    image: adminer
    container_name: tcc-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: